//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssignmentWPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryAssignmentWPF.Resex", typeof(Resex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        internal static string btnAddBook {
            get {
                return ResourceManager.GetString("btnAddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        internal static string btnAddCart {
            get {
                return ResourceManager.GetString("btnAddCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Journal.
        /// </summary>
        internal static string btnAddJournal {
            get {
                return ResourceManager.GetString("btnAddJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string btnCart {
            get {
                return ResourceManager.GetString("btnCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string btnCheckOut {
            get {
                return ResourceManager.GetString("btnCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer to Club.
        /// </summary>
        internal static string btnClub {
            get {
                return ResourceManager.GetString("btnClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Club Customers.
        /// </summary>
        internal static string btnClubCustomers {
            get {
                return ResourceManager.GetString("btnClubCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Club Discount.
        /// </summary>
        internal static string btnClubDiscount {
            get {
                return ResourceManager.GetString("btnClubDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Book.
        /// </summary>
        internal static string btnEditBook {
            get {
                return ResourceManager.GetString("btnEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Journal.
        /// </summary>
        internal static string btnEditJournal {
            get {
                return ResourceManager.GetString("btnEditJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string btnEnter {
            get {
                return ResourceManager.GetString("btnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Items By Name.
        /// </summary>
        internal static string btnFind {
            get {
                return ResourceManager.GetString("btnFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Main Menu.
        /// </summary>
        internal static string btnMainMenu {
            get {
                return ResourceManager.GetString("btnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Book Receipts.
        /// </summary>
        internal static string btnManageBooks {
            get {
                return ResourceManager.GetString("btnManageBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage System Exceptions.
        /// </summary>
        internal static string btnManageExceptions {
            get {
                return ResourceManager.GetString("btnManageExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Journal Receipts.
        /// </summary>
        internal static string btnManageJournals {
            get {
                return ResourceManager.GetString("btnManageJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string btnPay {
            get {
                return ResourceManager.GetString("btnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Purchases.
        /// </summary>
        internal static string btnPurcchases {
            get {
                return ResourceManager.GetString("btnPurcchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Book.
        /// </summary>
        internal static string btnRemoveBook {
            get {
                return ResourceManager.GetString("btnRemoveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Cart.
        /// </summary>
        internal static string btnRemoveCart {
            get {
                return ResourceManager.GetString("btnRemoveCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Customer From Club.
        /// </summary>
        internal static string btnRemoveCustomer {
            get {
                return ResourceManager.GetString("btnRemoveCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Journal.
        /// </summary>
        internal static string btnRemoveJournal {
            get {
                return ResourceManager.GetString("btnRemoveJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string btnReturn {
            get {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Book.
        /// </summary>
        internal static string btnSellBook {
            get {
                return ResourceManager.GetString("btnSellBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Items.
        /// </summary>
        internal static string btnSellItems {
            get {
                return ResourceManager.GetString("btnSellItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Journal.
        /// </summary>
        internal static string btnSellJournal {
            get {
                return ResourceManager.GetString("btnSellJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Available Books.
        /// </summary>
        internal static string btnShowBooks {
            get {
                return ResourceManager.GetString("btnShowBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Available Items.
        /// </summary>
        internal static string btnShowItems {
            get {
                return ResourceManager.GetString("btnShowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Available Journals.
        /// </summary>
        internal static string btnShowJournals {
            get {
                return ResourceManager.GetString("btnShowJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Word.
        /// </summary>
        internal static string btnWord {
            get {
                return ResourceManager.GetString("btnWord", resourceCulture);
            }
        }
    }
}
